version: '3.9'

services:

  nethermind:
    image: nethermind/nethermind
    restart: unless-stopped
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
    environment:
      - NETHERMIND_CONFIG=xdai
      - NETHERMIND_JSONRPCCONFIG_ENABLED=true
      - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
      - NETHERMIND_HEALTHCHECKSCONFIG_ENABLED=true
      - NETHERMIND_JSONRPCCONFIG_ENABLEDMODULES=[Eth, Mev, Web3]
      - NETHERMIND_SYNCCONFIG_FASTSYNC=true
      - NETHERMIND_SYNCCONFIG_FASTBLOCKS=true
      - NETHERMIND_METRICSCONFIG_ENABLED=true
    volumes:
      - nethermind:/nethermind/nethermind_db
      - nethermind:/nethermind/keystore
      - nethermind:/nethermind/Data
      - nethermind:/nethermind/logs
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30


  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 2048M
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: "http://localhost:3100/loki/api/v1/push"

  clef:
    image: ethersphere/clef
    command: full
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=100
    volumes:
      - ./bee-clef:/app/data

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://localhost:3100/loki/api/v1/push"

  bee:
    image: ethersphere/bee
    command: start
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1633
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE=false
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=10000000
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR=:1635
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE=true
      - BEE_NETWORK_ID=1
      - BEE_P2P_ADDR=:1634
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD_FILE=/password
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT=https://dai.poa.network
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE=Hello
      - BEE_MAINNET=true
    ports:
      - 1633:1633
      - 1634:1634
      - 1635:1635
    healthcheck:
      test: wget http://localhost:1633
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - ./bee:/home/bee/.bee
      - ./bee-clef/password:/password
    depends_on:
      - clef

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1024M
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://localhost:3100/loki/api/v1/push"

  # loki:
  #   image: grafana/loki:2.4.1
  #   restart: unless-stopped
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ${PWD}/loki.yaml:/etc/loki/local-config.yaml
  #     - loki:/loki
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - loki

  # promtail:
  #   image: grafana/promtail:2.4.1
  #   restart: unless-stopped
  #   volumes:
  #     - ${PWD}/promtail.yaml:/etc/promtail/config.yml
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - loki

  # grafana:
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana:/var/lib/grafana
  #   environment:
  #     - GF_AUTH_DISABLE_LOGIN_FORM=true
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_SECURITY_ALLOW_EMBEDDING=true
  #   networks:
  #     - loki

networks:
  loki:
  
volumes:
  loki:
  grafana:
  nethermind: