version: '3.9'

services:

  clef:
    image: ethersphere/clef:0.13.1
    command: full
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=100
    volumes:
      - ./bee-clef:/app/data


  bee:
    image: ethersphere/bee:1.8.2
    command: start
    restart: unless-stopped
    environment:
      - BEE_API_ADDR=:1633
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE=false
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=10000000
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR=:1635
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE=false
      - BEE_NETWORK_ID=1
      - BEE_P2P_ADDR=:1634
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD_FILE=/password
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT=https://xdai.fairdatasociety.org
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE=Hello
      - BEE_MAINNET=true
    ports:
      - 1633:1633
      - 1634:1634
      - 1635:1635
    healthcheck:
      test: wget http://localhost:1633
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - ./bee:/home/bee/.bee
      - ./bee-clef/password:/password
    depends_on:
      - clef